In [1]:
import pandas as pd

In [2]:
pd.__version__

'2.3.0'

In [3]:
df = pd.read_csv('https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/car_fuel_efficiency_2026.csv')

In [4]:
df.head()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   model_year           10000 non-null  int64
 1   origin               10000 non-null  object
 2   fuel_type            10000 non-null  object
 3   drivetrain           10000 non-null  object
 4   num_doors            10000 non-null  int64
 5   engine_displacement  10000 non-null  int64
 6   num_cylinders        10000 non-null  int64
 7   horsepower           9123 non-null   float64
 8   vehicle_weight       10000 non-null  int64
 9   acceleration         9736 non-null   float64
 10  fuel_efficiency_mpg  10000 non-null  float64
dtypes: float64(3), int64(5), object(3)
memory usage: 859.5+ KB

In [8]:
df['fuel_type'].unique()

array(['Gasoline', 'Diesel', 'Hybrid'], dtype=object)

In [10]:
df.isnull().sum()

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower             877
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

In [13]:
df[df['origin'] == 'Asia'].sort_values(by='fuel_efficiency_mpg',ascending=False)

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
6354,2022,Asia,Diesel,Front-wheel drive,4,1990,6,225.0,3870,17.2,41.2
4077,2017,Asia,Hybrid,Front-wheel drive,5,2060,6,196.0,3910,19.4,39.8
2181,2016,Asia,Hybrid,Front-wheel drive,3,2320,6,241.0,4020,18.9,39.2
1800,2019,Asia,Hybrid,Front-wheel drive,4,1780,5,213.0,3690,19.7,39.2
5720,2021,Asia,Hybrid,Front-wheel drive,4,1940,6,211.0,4100,19.3,39.1
...,...,...,...,...,...,...,...,...,...,...,...
9077,1991,Asia,Gasoline,All-wheel drive,5,2250,6,269.0,4240,16.9,22.8
4702,1981,Asia,Gasoline,Rear-wheel drive,2,2530,7,280.0,4440,18.3,22.7
2832,1980,Asia,Gasoline,Rear-wheel drive,3,2670,7,273.0,4690,17.9,22.5
2696,1977,Asia,Gasoline,Front-wheel drive,4,2590,7,276.0,4660,20.0,21.9
5155,1976,Asia,Gasoline,All-wheel drive,5,2670,7,NaN,4900,19.5,21.3

In [16]:
df[df['horsepower'] == df['horsepower'].median()]

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
26,1990,Europe,Gasoline,Front-wheel drive,3,2330,7,254.0,4040,18.8,28.6
37,1983,Europe,Gasoline,Rear-wheel drive,2,2420,6,254.0,4360,19.5,28.2
65,2018,Asia,Gasoline,Front-wheel drive,2,2180,6,254.0,3970,18.3,35.6
71,2015,USA,Gasoline,Rear-wheel drive,4,2160,6,254.0,4350,18.1,28.9
119,1991,Asia,Hybrid,Rear-wheel drive,3,2180,5,254.0,4090,19.6,32.7
...,...,...,...,...,...,...,...,...,...,...,...
9616,1996,Europe,Hybrid,Front-wheel drive,4,2460,7,254.0,4490,NaN,34.1
9743,2003,Europe,Diesel,Rear-wheel drive,4,2380,6,254.0,4510,21.5,30.3
9775,2022,Europe,Hybrid,Front-wheel drive,2,2250,6,254.0,4410,17.2,36.3
9849,1992,USA,Gasoline,Front-wheel drive,3,2220,6,254.0,4400,18.6,25.9
9922,1995,USA,Diesel,Front-wheel drive,2,2300,6,254.0,4270,18.6,31.5

In [21]:
df_full = df['horsepower'].fillna(df['horsepower'].mode())
df_full[df_full == df_full.median()]

26      254.0
37      254.0
65      254.0
71      254.0
119     254.0
        ...
9616    254.0
9743    254.0
9775    254.0
9849    254.0
9922    254.0
Name: horsepower, Length: 155, dtype: float64

In [30]:
df_select = df[df['origin'] == 'Asia']
df_select = df_select.iloc[:7,[0,8]]

In [34]:
df_select.head(8)

    model_year  vehicle_weight
2         1996            4240
6         1992            4310
8         1997            4230
10        1978            4420
15        2007            3950
16        2021            4750
22        2019            4450

In [37]:
import numpy as np
x = np.array(df_select)

In [38]:
XTX = np.matmul(x.T,x)
XTX_inv = np.linalg.inv(calc)

In [39]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])

In [40]:
w = np.matmul(np.matmul(calc,x.T),y)

In [41]:
np.sum(w)

np.int64(7509716967583600)